# Generated by Django 5.0.6 on 2024-06-19 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client", "0004_rename_number_client_tel_number"),
        ("team", "0003_alter_team_rcs_alter_team_siret_alter_team_tva_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("client_email", models.CharField(max_length=255)),
                (
                    "client_siret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("client_cp", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "client_pays",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("Facture", "Facture"), ("Devis", "Devis")],
                        default="Facture",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("total_ht", models.DecimalField(decimal_places=2, max_digits=6)),
                ("total_tva", models.DecimalField(decimal_places=2, max_digits=6)),
                ("total_ttc", models.DecimalField(decimal_places=2, max_digits=6)),
                ("reduction", models.DecimalField(decimal_places=2, max_digits=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factures",
                        to="client.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creater_factures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_factures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factures",
                        to="team.team",
                    ),
                ),
            ],
        ),
    ]
