# Generated by Django 5.0.6 on 2024-06-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="reduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
