# Generated by Django 5.0.6 on 2024-06-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0003_invoice_is_paid_alter_invoice_reduction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="invoice",
            name="tva_20",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tva_5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
