# Generated by Django 5.0.6 on 2024-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0004_alter_invoice_options_invoice_tva_20_invoice_tva_5"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="client_company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
