# Generated by Django 5.0.6 on 2024-06-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0005_invoice_client_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="client_ville",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
