# Generated by Django 5.0.6 on 2024-06-19 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0006_invoice_client_ville"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="client_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="client_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="invoice.invoice",
            ),
        ),
    ]
