# Generated by Django 5.0.6 on 2024-06-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "invoice",
            "0007_alter_invoice_client_email_alter_invoice_client_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total_ht",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_tva",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
