# Generated by Django 5.0.6 on 2024-06-20 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0012_alter_invoice_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="team",
        ),
    ]
