# Generated by Django 5.0.6 on 2024-06-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0016_invoice_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
