# Generated by Django 5.0.6 on 2024-06-27 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_quantity_alter_product_tva"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
