# Generated by Django 5.0.6 on 2024-06-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
