# Generated by Django 5.0.6 on 2024-06-14 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_client_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="number",
            new_name="tel_number",
        ),
    ]
