# Generated by Django 5.0.6 on 2024-06-26 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_rename_number_client_tel_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=255)),
                ("is_paid", models.BooleanField(default=False)),
                ("total_ht", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                ("invoice_type", models.CharField(max_length=255)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="client.client",
                    ),
                ),
            ],
        ),
    ]
