# Generated by Django 5.0.6 on 2024-06-26 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0005_invoice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
