# Generated by Django 5.0.6 on 2024-06-14 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("code_postal", models.CharField(max_length=255)),
                ("ville", models.CharField(max_length=255)),
                ("pays", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("RCS", models.CharField(max_length=255)),
                ("SIRET", models.CharField(max_length=255)),
                ("TVA", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
