# Generated by Django 5.0.6 on 2024-06-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_rename_teams_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="RCS",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="SIRET",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="TVA",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="code_postal",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="pays",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="ville",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
