# Generated by Django 5.0.6 on 2024-06-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0003_alter_team_rcs_alter_team_siret_alter_team_tva_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="BIC",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="IBAN",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="bank",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
